/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1.0/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Heartbeat
         * @description This route is used to check the server is up and running.
         */
        get: operations["heartbeat_v1_0_heartbeat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1.0/db-heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Db Heartbeat
         * @description This route is used to check the connection to the database is working.
         */
        get: operations["db_heartbeat_v1_0_db_heartbeat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1.0/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versions
         * @description This route returns the version of the current running API.
         */
        get: operations["versions_v1_0_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Layers
         * @description List layers.
         */
        get: operations["list_layers_layers_get"];
        put?: never;
        /**
         * Create Layer
         * @description Create layer.
         */
        post: operations["create_layer_layers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{layer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Layer
         * @description Get a layer by id.
         */
        get: operations["get_layer_layers__layer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Nodes
         * @description List nodes filtered by layer_id OR parent_node_id (not both) with pagination.
         */
        get: operations["list_nodes_nodes_get"];
        put?: never;
        /**
         * Create Node
         * @description Create node.
         */
        post: operations["create_node_nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node
         * @description Get node by id.
         */
        get: operations["get_node_nodes__node_id__get"];
        /**
         * Update Node
         * @description Update node.
         */
        put: operations["update_node_nodes__node_id__put"];
        post?: never;
        /**
         * Delete Node
         * @description Delete node.
         */
        delete: operations["delete_node_nodes__node_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Bulk Update Node
         * @description Update node.
         */
        put: operations["bulk_update_node_nodes_bulk_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/{layer_id}/{z}/{x}/{y}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tile
         * @description Get a vector tile for a specific layer at the given tile coordinates.
         *
         *     Args:
         *         layer_id: The layer ID to render nodes from
         *         z: Zoom level
         *         x: Tile X coordinate
         *         y: Tile Y coordinate
         *         db: Database session
         *
         *     Returns:
         *         Mapbox Vector Tile (MVT) in protobuf format
         */
        get: operations["get_tile_tiles__layer_id___z___x___y__pbf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/debug/colors/{layer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug Layer Colors
         * @description Debug endpoint to check if color values exist in the database.
         */
        get: operations["debug_layer_colors_tiles_debug_colors__layer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/debug/tile/{layer_id}/{z}/{x}/{y}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug Tile Data
         * @description Debug endpoint to see what data would be in a tile (as JSON instead of MVT).
         */
        get: operations["debug_tile_data_tiles_debug_tile__layer_id___z___x___y__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tile Layers
         * @description List all available layers that can be rendered as tiles.
         *
         *     Returns a list of layers with their IDs and names, which can be used
         *     to construct tile URLs.
         */
        get: operations["list_tile_layers_tiles_layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/diagnostics/geometry-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Geometry Stats
         * @description Get detailed statistics about polygon complexity to diagnose performance issues.
         *
         *     This endpoint helps identify problematic geometries that might be causing
         *     database crashes or slow queries.
         */
        get: operations["get_geometry_stats_tiles_diagnostics_geometry_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/diagnostics/problematic-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Problematic Nodes
         * @description List nodes with overly complex geometries that might cause performance issues.
         *
         *     Args:
         *         db: Database session
         *         layer_id: Optional layer to filter by
         *         min_points: Minimum number of points to be considered problematic (default: 10000)
         */
        get: operations["get_problematic_nodes_tiles_diagnostics_problematic_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/diagnostics/node-stats/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Stats
         * @description Get detailed statistics about a specific node's geometry.
         *
         *     Args:
         *         node_id: The node ID to analyze
         *         db: Database session
         *
         *     Returns:
         *         Dictionary with detailed geometry statistics including:
         *         - size_bytes: Raw geometry size in bytes
         *         - size_kb: Geometry size in kilobytes
         *         - num_vertices: Total number of vertices across all polygons
         *         - num_polygons: Number of polygons in the multipolygon
         *         - num_rings: Total number of rings (exterior + interior/holes)
         *         - avg_vertices_per_polygon: Average vertices per polygon
         *         - min_distance: Minimum distance between consecutive points (meters)
         *         - max_distance: Maximum distance between consecutive points (meters)
         *         - avg_distance: Average distance between consecutive points (meters)
         *         - median_distance: Median distance between consecutive points (meters)
         *         - coordinate_precision: Estimated decimal places in coordinates
         *         - is_valid: Whether geometry is topologically valid
         *         - invalid_reason: Reason if geometry is invalid
         */
        get: operations["get_node_stats_tiles_diagnostics_node_stats__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Map
         * @description Create map.
         *
         *     TOODS:
         *         - Return errors for zip codes we don't have data for
         *         - Validate no duplicate layer names
         *         - Validate no duplicate parents and raise error if so
         *         - Fix all typing issues
         *         - Recompute after loading zip codes
         *         - Add data fields
         */
        post: operations["create_map_maps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BulkUpdateNode
         * @description BulkUpdateNode.
         */
        BulkUpdateNode: {
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Id */
            id: number;
        };
        /**
         * CreateLayer
         * @description CreateLayer.
         */
        CreateLayer: {
            /** Name */
            name: string;
        };
        /**
         * CreateNode
         * @description CreateNode.
         */
        CreateNode: {
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Layer Id */
            layer_id: number;
        };
        /**
         * DataFieldSetup
         * @description DataFieldSetup.
         */
        DataFieldSetup: {
            /** Name */
            name: string;
            /** Header */
            header: string;
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "number";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeartbeatResponseDTO
         * @description Heartbeat response DTO.
         */
        HeartbeatResponseDTO: {
            /**
             * Timenow
             * Format: date-time
             */
            timenow: string;
        };
        /**
         * ImportMap
         * @description ImportMap.
         */
        ImportMap: {
            /** Name */
            name: string;
            /** Layers */
            layers: components["schemas"]["LayerSetup"][];
            /** Data Fields */
            data_fields: components["schemas"]["DataFieldSetup"][];
            /** Values */
            values: (string | number | null)[][];
            /** Headers */
            headers: string[];
        };
        /**
         * ImportMapResponse
         * @description ImportMapResponse.
         */
        ImportMapResponse: {
            /** Map Id */
            map_id: number;
        };
        /**
         * LayerSetup
         * @description LayerSetup.
         */
        LayerSetup: {
            /** Name */
            name: string;
            /** Header */
            header: string;
        };
        /**
         * UpdateNode
         * @description UpdateNode.
         */
        UpdateNode: {
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionResponseDTO
         * @description Version response DTO.
         */
        VersionResponseDTO: {
            /** Api */
            api: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    heartbeat_v1_0_heartbeat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponseDTO"];
                };
            };
        };
    };
    db_heartbeat_v1_0_db_heartbeat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    versions_v1_0_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponseDTO"];
                };
            };
        };
    };
    list_layers_layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_layer_layers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLayer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layer_layers__layer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_nodes_nodes_get: {
        parameters: {
            query?: {
                layer_id?: number | null;
                parent_node_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_node_nodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNode"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_node_nodes__node_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNode"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_node_nodes__node_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_node_nodes_bulk_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUpdateNode"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tile_tiles__layer_id___z___x___y__pbf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_layer_colors_tiles_debug_colors__layer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_tile_data_tiles_debug_tile__layer_id___z___x___y__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tile_layers_tiles_layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_geometry_stats_tiles_diagnostics_geometry_stats_get: {
        parameters: {
            query?: {
                layer_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_problematic_nodes_tiles_diagnostics_problematic_nodes_get: {
        parameters: {
            query?: {
                layer_id?: number | null;
                min_points?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_stats_tiles_diagnostics_node_stats__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_map_maps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportMap"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportMapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
