/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Heartbeat
         * @description This route is used to check the server is up and running.
         */
        get: operations["heartbeat_heartbeat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/db-heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Db Heartbeat
         * @description This route is used to check the connection to the database is working.
         */
        get: operations["db_heartbeat_db_heartbeat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versions
         * @description This route returns the version of the current running API.
         */
        get: operations["versions_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login user and set JWT cookies.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh the access token using the refresh token.
         */
        post: operations["refresh_token_auth_refresh_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout user by clearing the auth cookie.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get the currently logged in user.
         */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Layers
         * @description List layers.
         */
        get: operations["list_layers_layers_get"];
        put?: never;
        /**
         * Create Layer
         * @description Create layer.
         */
        post: operations["create_layer_layers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{layer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Layer
         * @description Get a layer by id.
         */
        get: operations["get_layer_layers__layer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Nodes
         * @description List nodes filtered by layer_id OR parent_node_id (not both) with pagination.
         *
         *     Only applies to order>=1 layers. For order=0 (zip layer) use GET /zip-assignments.
         */
        get: operations["list_nodes_nodes_get"];
        put?: never;
        /**
         * Create Node
         * @description Create node.
         */
        post: operations["create_node_nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node
         * @description Get node by id.
         */
        get: operations["get_node_nodes__node_id__get"];
        /**
         * Update Node
         * @description Update node.
         */
        put: operations["update_node_nodes__node_id__put"];
        post?: never;
        /**
         * Delete Node
         * @description Delete a node (order>=1 only). Cascades to child nodes via FK.
         */
        delete: operations["delete_node_nodes__node_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Bulk Update Node
         * @description Bulk update nodes.
         */
        put: operations["bulk_update_node_nodes_bulk_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zip-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Zip Assignments
         * @description List zip assignments for an order=0 layer, optionally filtered by parent territory.
         */
        get: operations["list_zip_assignments_zip_assignments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zip-assignments/{layer_id}/{zip_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Zip Assignment
         * @description Get the assignment state of a specific zip code. Returns 404 if the zip is implicitly unassigned.
         */
        get: operations["get_zip_assignment_zip_assignments__layer_id___zip_code__get"];
        /**
         * Assign Zip
         * @description Assign a zip code to a territory, or update an existing assignment.
         *
         *     Passing parent_node_id=null unassigns the zip (preserves the row and color).
         */
        put: operations["assign_zip_zip_assignments__layer_id___zip_code__put"];
        post?: never;
        /**
         * Reset Zip
         * @description Reset a zip code to its default state (removes the assignment row).
         *
         *     The zip remains implicitly present on the map but reverts to white with no territory.
         */
        delete: operations["reset_zip_zip_assignments__layer_id___zip_code__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zip-assignments/{layer_id}/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Bulk Assign Zips
         * @description Bulk assign or unassign zip codes to a territory.
         *
         *     Primary operation after lasso selection. Passing parent_node_id=null
         *     unassigns all provided zip codes (preserves rows and colors).
         */
        put: operations["bulk_assign_zips_zip_assignments__layer_id__bulk_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zip-assignments/{layer_id}/{zip_code}/geography": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Zip With Geography Default
         * @description Get a zip's assignment state, falling back to geography defaults if no row exists.
         *
         *     Unlike GET /zip-assignments/{layer_id}/{zip_code}, this never returns 404 for
         *     known zip codes — it returns the implicit white/unassigned state.
         */
        get: operations["get_zip_with_geography_default_zip_assignments__layer_id___zip_code__geography_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/{layer_id}/{z}/{x}/{y}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tile
         * @description Get a vector tile for a specific layer at the given tile coordinates.
         *
         *     For order=0 (zip) layers: queries geography_zip_codes LEFT JOIN zip_assignments.
         *     For order>=1 layers: queries pre-computed node geometries.
         */
        get: operations["get_tile_tiles__layer_id___z___x___y__pbf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/{layer_id}/{z}/{x}/{y}/labels.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Label Tile
         * @description Get a label tile for a specific layer using point-on-surface geometries.
         *
         *     For order=0 (zip) layers: one point per zip code, label is the zip_code string.
         *     For order>=1 layers: one point per node with all configured data field values.
         */
        get: operations["get_label_tile_tiles__layer_id___z___x___y__labels_pbf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tile Layers
         * @description List all available layers that can be rendered as tiles.
         *
         *     Returns a list of layers with their IDs and names, which can be used
         *     to construct tile URLs.
         */
        get: operations["list_tile_layers_tiles_layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Maps
         * @description List maps.
         */
        get: operations["list_maps_maps_get"];
        put?: never;
        /**
         * Create Map
         * @description Create map.
         *
         *     TODO:
         *         - Return errors for zip codes we don't have data for
         *         - Validate no duplicate layer names
         *         - Validate no duplicate parents and raise error if so
         */
        post: operations["create_map_maps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spatial/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select Features In Lasso
         * @description Select all features from a layer that intersect with a lasso polygon.
         *
         *     For order=0 (zip) layers: returns zip_codes (strings) from geography_zip_codes.
         *     For order>=1 layers: returns node IDs (integers) from nodes.
         */
        post: operations["select_features_in_lasso_spatial_select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssignZip
         * @description Assign or update a single zip code's territory assignment.
         *
         *     PUT with parent_node_id=null unassigns the zip (nulls the FK, preserves the row and color).
         *     DELETE /layers/{layer_id}/zips/{zip_code} resets the zip (removes the row entirely).
         */
        AssignZip: {
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Color */
            color?: string | null;
        };
        /**
         * BulkAssignZips
         * @description Bulk assign or unassign a list of zip codes to a territory.
         *
         *     Primary operation after lasso selection: select zips on map, assign to territory.
         *     parent_node_id=null unassigns all provided zip codes (preserves rows and colors).
         */
        BulkAssignZips: {
            /** Zip Codes */
            zip_codes: string[];
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Color */
            color?: string | null;
        };
        /**
         * BulkUpdateNode
         * @description BulkUpdateNode.
         */
        BulkUpdateNode: {
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Id */
            id: number;
        };
        /**
         * CreateLayer
         * @description CreateLayer.
         */
        CreateLayer: {
            /** Name */
            name: string;
            /** Map Id */
            map_id: number;
        };
        /**
         * CreateNode
         * @description CreateNode.
         */
        CreateNode: {
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Layer Id */
            layer_id: number;
        };
        /**
         * DataFieldConfig
         * @description Data field config entry stored on a map.
         */
        DataFieldConfig: {
            /** Field */
            field: string;
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "number";
            /** Aggregations */
            aggregations: ("sum" | "avg")[];
        };
        /**
         * DataFieldSetup
         * @description DataFieldSetup.
         */
        DataFieldSetup: {
            /** Name */
            name: string;
            /** Header */
            header: string;
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "number";
            /**
             * Aggregations
             * @default []
             */
            aggregations: ("sum" | "avg")[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeartbeatResponseDTO
         * @description Heartbeat response DTO.
         */
        HeartbeatResponseDTO: {
            /**
             * Timenow
             * Format: date-time
             */
            timenow: string;
        };
        /**
         * ImportMap
         * @description ImportMap.
         */
        ImportMap: {
            /** Name */
            name: string;
            /** Layers */
            layers: components["schemas"]["LayerSetup"][];
            /** Data Fields */
            data_fields: components["schemas"]["DataFieldSetup"][];
            /** Values */
            values: (string | number | null)[][];
            /** Headers */
            headers: string[];
        };
        /**
         * Layer
         * @description Layer.
         */
        Layer: {
            /** Id */
            id: number;
            /** Map Id */
            map_id: number;
            /** Name */
            name: string;
            /** Order */
            order: number;
        };
        /**
         * LayerSetup
         * @description LayerSetup.
         */
        LayerSetup: {
            /** Name */
            name: string;
            /** Header */
            header: string;
        };
        /**
         * LoginDTO
         * @description POST model for logging in a user.
         */
        LoginDTO: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Remember Me
             * @default false
             */
            remember_me: boolean;
        };
        /**
         * Map
         * @description Map.
         */
        Map: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Data Field Config */
            data_field_config?: components["schemas"]["DataFieldConfig"][] | null;
        };
        /**
         * Node
         * @description Node.
         */
        Node: {
            /** Id */
            id: number | "default";
            /** Layer Id */
            layer_id: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Parent Node Id */
            parent_node_id?: number | null;
            /**
             * Child Count
             * @default 0
             */
            child_count: number;
        };
        /**
         * PaginatedNodes
         * @description Paginated nodes response.
         */
        PaginatedNodes: {
            /** Nodes */
            nodes: components["schemas"]["Node"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PaginatedZipAssignments
         * @description Paginated zip assignments response.
         */
        PaginatedZipAssignments: {
            /** Zip Assignments */
            zip_assignments: components["schemas"]["ZipAssignment"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * Polygon
         * @description Polygon Model
         */
        Polygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][];
        };
        Position2D: [
            number,
            number
        ];
        Position3D: [
            number,
            number,
            number
        ];
        /**
         * RegisterDTO
         * @description POST model for creating a new user.
         */
        RegisterDTO: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** SpatialSelectRequest */
        SpatialSelectRequest: {
            /** Layer Id */
            layer_id: number;
            polygon: components["schemas"]["Polygon"];
        };
        /** SpatialSelectResponse */
        SpatialSelectResponse: {
            /** Count */
            count: number;
            /** Nodes */
            nodes: number[];
            /**
             * Zip Codes
             * @default []
             */
            zip_codes: string[];
        };
        /**
         * UpdateNode
         * @description UpdateNode.
         */
        UpdateNode: {
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /**
         * User
         * @description User schema.
         */
        User: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionResponseDTO
         * @description Version response DTO.
         */
        VersionResponseDTO: {
            /** Api */
            api: string | null;
        };
        /**
         * ZipAssignment
         * @description A zip code's assignment state on a map layer.
         *
         *     Represents a zip_assignments row. Implicit zips (no row) are only visible
         *     via MVT tiles and are not returned by the API as individual objects.
         */
        ZipAssignment: {
            /** Zip Code */
            zip_code: string;
            /** Layer Id */
            layer_id: number;
            /** Parent Node Id */
            parent_node_id?: number | null;
            /** Color */
            color: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    heartbeat_heartbeat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponseDTO"];
                };
            };
        };
    };
    db_heartbeat_db_heartbeat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    versions_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponseDTO"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_auth_refresh_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    list_layers_layers_get: {
        parameters: {
            query: {
                map_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_layer_layers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLayer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layer_layers__layer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_nodes_nodes_get: {
        parameters: {
            query?: {
                layer_id?: number | null;
                parent_node_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNodes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_node_nodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNode"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_node_nodes__node_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNode"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_node_nodes__node_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_node_nodes_bulk_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUpdateNode"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_zip_assignments_zip_assignments_get: {
        parameters: {
            query: {
                layer_id: number;
                parent_node_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedZipAssignments"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zip_assignment_zip_assignments__layer_id___zip_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                zip_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZipAssignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_zip_zip_assignments__layer_id___zip_code__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                zip_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignZip"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZipAssignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_zip_zip_assignments__layer_id___zip_code__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                zip_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_assign_zips_zip_assignments__layer_id__bulk_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkAssignZips"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zip_with_geography_default_zip_assignments__layer_id___zip_code__geography_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                zip_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZipAssignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tile_tiles__layer_id___z___x___y__pbf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_label_tile_tiles__layer_id___z___x___y__labels_pbf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tile_layers_tiles_layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_maps_maps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Map"][];
                };
            };
        };
    };
    create_map_maps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportMap"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Map"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_features_in_lasso_spatial_select_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpatialSelectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialSelectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
