"""add alembic history log.

Revision ID: ade4809321e2
Revises:
Create Date: 2024-11-06 23:02:58.369458-08:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ade4809321e2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade revisions: None to ade4809321e2."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alembic_version_history",
        sa.Column("version_num", sa.String(100), nullable=False),
        sa.Column("message", sa.String()),
        sa.Column("type", sa.Enum("UPGRADE", "DOWNGRADE", native_enum=False), nullable=False),
        sa.Column("migrated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade revisions: ade4809321e2 to None."""
    # ### commands auto generated by Alembic - please adjust! ###
    print("This downgrade does not drop the table: alembic_version_history. Manually drop it if required.")
    # ### end Alembic commands ###
