"""init models.

Revision ID: e0208f3fbddd
Revises: faabb954ac33
Create Date: 2025-11-24 21:41:57.613863-08:00

"""

from collections.abc import Sequence
from typing import TYPE_CHECKING, cast

from alembic import op as _op

if TYPE_CHECKING:
    from geoalchemy2.alembic_helpers import GeoAlchemyOperations

    op: GeoAlchemyOperations = cast("GeoAlchemyOperations", _op)
else:
    op = _op  # type: ignore[assignment]
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e0208f3fbddd"
down_revision: str | None = "faabb954ac33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade revisions: faabb954ac33 to e0208f3fbddd."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "layers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("parent_layer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_layer_id"], ["layers.id"], name=op.f("fk_layers_parent_layer_id_layers")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_layers")),
        sa.UniqueConstraint("name", name=op.f("uq_layers_name")),
        sa.UniqueConstraint("order", name=op.f("uq_layers_order")),
    )
    op.create_geospatial_table(
        "nodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("layer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "geom",
            Geometry(srid=4326, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.ForeignKeyConstraint(["layer_id"], ["layers.id"], name=op.f("fk_nodes_layer_id_layers")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
    )
    op.create_geospatial_index(
        "idx_nodes_geom", "nodes", ["geom"], unique=False, postgresql_using="gist", postgresql_ops={}
    )
    op.create_table(
        "layer_entity_dependencies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["child_id"], ["nodes.id"], name=op.f("fk_layer_entity_dependencies_child_id_nodes")),
        sa.ForeignKeyConstraint(["parent_id"], ["nodes.id"], name=op.f("fk_layer_entity_dependencies_parent_id_nodes")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_layer_entity_dependencies")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade revisions: e0208f3fbddd to faabb954ac33."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("layer_entity_dependencies")
    op.drop_geospatial_index("idx_nodes_geom", table_name="nodes", postgresql_using="gist", column_name="geom")
    op.drop_geospatial_table("nodes")
    op.drop_table("layers")
    # ### end Alembic commands ###
