"""added cache keys.

Revision ID: f2a18cd05824
Revises: 06888d063b01
Create Date: 2025-11-26 18:39:42.053856-08:00

"""

from collections.abc import Sequence
from typing import TYPE_CHECKING, cast

from alembic import op as _op

if TYPE_CHECKING:
    from geoalchemy2.alembic_helpers import GeoAlchemyOperations

    op: GeoAlchemyOperations = cast("GeoAlchemyOperations", _op)
else:
    op = _op  # type: ignore[assignment]
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f2a18cd05824"
down_revision: str | None = "06888d063b01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade revisions: 06888d063b01 to f2a18cd05824."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("data_cache_key", sa.String(), nullable=False))
    op.add_column("nodes", sa.Column("data_inputs_cache_key", sa.String(), nullable=False))
    op.add_column("nodes", sa.Column("geom_cache_key", sa.String(), nullable=False))
    op.add_column("nodes", sa.Column("geom_inputs_cache_key", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade revisions: f2a18cd05824 to 06888d063b01."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "geom_inputs_cache_key")
    op.drop_column("nodes", "geom_cache_key")
    op.drop_column("nodes", "data_inputs_cache_key")
    op.drop_column("nodes", "data_cache_key")
    # ### end Alembic commands ###
