"""added zip code geography.

Revision ID: bd9a96a540db
Revises: f2a18cd05824
Create Date: 2025-12-28 09:59:24.701614-08:00

"""

from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING, cast

from alembic import op as _op
from geoalchemy2.shape import from_shape
from geopandas import GeoDataFrame, gpd
from shapely import MultiPoint, Point
from shapely.geometry import MultiPolygon, Polygon
from shapely.geometry.base import BaseGeometry

if TYPE_CHECKING:
    from geoalchemy2.alembic_helpers import GeoAlchemyOperations

    op: GeoAlchemyOperations = cast("GeoAlchemyOperations", _op)
else:
    op = _op  # type: ignore[assignment]
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy import insert

# revision identifiers, used by Alembic.
revision: str = "bd9a96a540db"
down_revision: str | None = "f2a18cd05824"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Load zip code topography data
zip_code_geography_gdf = gpd.read_file(Path(__file__).resolve().parent.parent / "data/20251228-us_zcta_topo.json")  # pyright: ignore[reportUnknownMemberType]


def normalize_geometry(geom: BaseGeometry | None):
    """Normalize geometry to ensure it's in the correct format."""
    if geom is None:
        return None
    if isinstance(geom, Polygon):
        geom = MultiPolygon([geom])
    elif isinstance(geom, MultiPolygon):
        pass
    elif isinstance(geom, Point):  # pyright: ignore[reportUnnecessaryIsInstance]
        geom = MultiPoint([geom])
    elif isinstance(geom, MultiPoint):
        pass
    else:
        return None
    if not geom.is_valid:
        geom = geom.buffer(0)
    return geom


def upgrade() -> None:
    """Upgrade revisions: f2a18cd05824 to bd9a96a540db."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "geography_zip_codes",
        sa.Column("zip_code", sa.String(length=5), nullable=False),
        sa.Column(
            "geom",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("zip_code", name=op.f("pk_geography_zip_codes")),
    )
    op.create_geospatial_index(
        "idx_geography_zip_codes_geom",
        "geography_zip_codes",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )

    connection = op.get_bind()

    df = zip_code_geography_gdf.copy()
    df["zip_code"] = df["zip"].astype(str).str.zfill(5)
    df = df[df["zip_code"] != "00000"]
    df = df[df["zip_code"].notna()]
    df = df.drop_duplicates(subset=["zip_code"], keep="first")
    df["geometry"] = df["geometry"].apply(normalize_geometry)  # pyright: ignore[reportUnknownMemberType, reportArgumentType, reportCallIssue]
    df = df[df["geometry"].notna()]  # pyright: ignore[reportUnknownMemberType]
    df = cast(GeoDataFrame, df[~df["geometry"].is_empty])
    df["geom"] = df["geometry"].apply(lambda g: bytes(from_shape(g, srid=4326).data))  # pyright: ignore[reportUnknownArgumentType, reportUnknownMemberType, reportUnknownLambdaType, reportArgumentType, reportCallIssue]
    zip_data_to_insert = df[["zip_code", "geom"]].to_dict("records")  # pyright: ignore[reportUnknownMemberType]
    batch_size = 5000
    total_inserted = 0

    for i in range(0, len(zip_data_to_insert), batch_size):
        batch = cast(list[dict[str, str]], zip_data_to_insert[i : i + batch_size])
        connection.execute(
            insert(
                sa.table(
                    "geography_zip_codes",
                    sa.column("zip_code"),
                    sa.column("geom"),
                )
            ),
            batch,  # pyright: ignore[reportArgumentType]
        )  # pyright: ignore[reportCallIssue]
        total_inserted += len(batch)


def downgrade() -> None:
    """Downgrade revisions: bd9a96a540db to f2a18cd05824."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_geography_zip_codes_geom", table_name="geography_zip_codes", postgresql_using="gist", column_name="geom"
    )
    op.drop_geospatial_table("geography_zip_codes")
    # ### end Alembic commands ###
