"""invite user flows.

Revision ID: 8947aba6c2c4
Revises: 5d2284c12aed
Create Date: 2026-04-29 19:10:07.734936-07:00

"""

from collections.abc import Sequence
from typing import TYPE_CHECKING, cast

from alembic import op as _op

if TYPE_CHECKING:
    from geoalchemy2.alembic_helpers import GeoAlchemyOperations

    op: GeoAlchemyOperations = cast("GeoAlchemyOperations", _op)
else:
    op = _op  # type: ignore[assignment]
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8947aba6c2c4"
down_revision: str | None = "5d2284c12aed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade revisions: 5d2284c12aed to 8947aba6c2c4."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map_invites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("map_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("invited_email", postgresql.CITEXT(), nullable=False),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("pending", "accepted", "declined", native_enum=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"], ["users.id"], name=op.f("fk_map_invites_invited_by_user_id_users")
        ),
        sa.ForeignKeyConstraint(["map_id"], ["maps.id"], name=op.f("fk_map_invites_map_id_maps")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_map_invites")),
    )
    op.create_index("idx_map_invites_invited_email", "map_invites", ["invited_email"], unique=False)
    op.create_index("idx_map_invites_map_id", "map_invites", ["map_id"], unique=False)
    op.create_index(
        "uq_map_invites_pending",
        "map_invites",
        ["map_id", "invited_email"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade revisions: 8947aba6c2c4 to 5d2284c12aed."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_map_invites_pending", table_name="map_invites", postgresql_where=sa.text("status = 'pending'"))
    op.drop_index("idx_map_invites_map_id", table_name="map_invites")
    op.drop_index("idx_map_invites_invited_email", table_name="map_invites")
    op.drop_table("map_invites")
    # ### end Alembic commands ###
