"""generate pptx async.

Revision ID: b4f840e887a6
Revises: 8947aba6c2c4
Create Date: 2026-04-29 20:31:51.930385-07:00

"""

from collections.abc import Sequence
from typing import TYPE_CHECKING, cast

from alembic import op as _op

if TYPE_CHECKING:
    from geoalchemy2.alembic_helpers import GeoAlchemyOperations

    op: GeoAlchemyOperations = cast("GeoAlchemyOperations", _op)
else:
    op = _op  # type: ignore[assignment]
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b4f840e887a6"
down_revision: str | None = "8947aba6c2c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade revisions: 8947aba6c2c4 to b4f840e887a6."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("map_exports", sa.Column("pptx_s3_key", sa.String(), nullable=True))
    op.add_column("map_exports", sa.Column("error", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade revisions: b4f840e887a6 to 8947aba6c2c4."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("map_exports", "error")
    op.drop_column("map_exports", "pptx_s3_key")
    # ### end Alembic commands ###
